version: 2
orbs:
  codecov: codecov/codecov@1.0.2jobs
jobs:
  build:
    docker:
      - image: circleci/python:3.6

    working_directory: ~/repo

    steps:
      - checkout
      
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install pytest
            pip install coverage
            pip install codecov
            pip install .
    
      - run:
          name: run unit tests
          command: |
            . venv/bin/activate
            mkdir test-reports
            coverage run --source=./metadict -m pytest --junitxml=test-reports/results.xml tests
            coverage report
            coverage html --directory=test-reports
            coverage xml
            mv coverage.xml test-reports
            codecov -f test-reports/coverage.xml

      - store_test_results:
          path: test-reports

      - store_artifacts:
          path: test-reports
          destination: test-reports
